LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE        := lm.smartcam.androidapp
LOCAL_MODULE_OWNER  := lm
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE_CLASS  := APPS
LOCAL_CERTIFICATE   := PRESIGNED
LOCAL_PRIVILEGED_MODULE := true
DONT_UNCOMPRESS_PRIV_APPS_DEXS := true
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
#LOCAL_NO_STANDARD_LIBRARIES := true
LOCAL_SRC_FILES     := $(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_PATH   := $(TARGET_OUT_APPS_PRIVILEGED)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE        := libLMLibEncDec
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB      := 64
LOCAL_MODULE_TAGS   := optional
LOCAL_SRC_FILES     := $(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_PATH   := $(TARGET_OUT_SHARED_LIBRARIES)
#LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE        := liblocee-jni
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB      := 64
#LOCAL_MODULE_OWNER  := lm
LOCAL_MODULE_TAGS   := optional
LOCAL_SRC_FILES     := $(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_PATH   := $(TARGET_OUT_SHARED_LIBRARIES)
#LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE        := libLMLibJni
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB      := 64
#LOCAL_MODULE_OWNER  := lm
LOCAL_MODULE_TAGS   := optional
LOCAL_SRC_FILES     := $(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_PATH   := $(TARGET_OUT_SHARED_LIBRARIES)
#LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE        := liblocee
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB      := 64
#LOCAL_MODULE_OWNER  := lm
LOCAL_MODULE_TAGS   := optional
LOCAL_SRC_FILES     := $(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_PATH   := $(TARGET_OUT_SHARED_LIBRARIES)
#LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_PREBUILT)
